package com.qoo.magicmirror.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.qoo.magicmirror.db.MainPageData;

import com.qoo.magicmirror.db.MainPageDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mainPageDataDaoConfig;

    private final MainPageDataDao mainPageDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mainPageDataDaoConfig = daoConfigMap.get(MainPageDataDao.class).clone();
        mainPageDataDaoConfig.initIdentityScope(type);

        mainPageDataDao = new MainPageDataDao(mainPageDataDaoConfig, this);

        registerDao(MainPageData.class, mainPageDataDao);
    }
    
    public void clear() {
        mainPageDataDaoConfig.getIdentityScope().clear();
    }

    public MainPageDataDao getMainPageDataDao() {
        return mainPageDataDao;
    }

}
