package com.qoo.magicmirror.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MAIN_PAGE_DATA".
 */
public class MainPageData {

    private Long id;
    private String path;
    private String name;
    private String area;
    private String price;
    private String brand;
    private String type;

    public MainPageData() {
    }

    public MainPageData(Long id) {
        this.id = id;
    }

    public MainPageData(Long id, String path, String name, String area, String price, String brand, String type) {
        this.id = id;
        this.path = path;
        this.name = name;
        this.area = area;
        this.price = price;
        this.brand = brand;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
